name: Azure Functions CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Build and deploy to Azure Functions
        env:
          AZURE_FUNCTIONAPP_NAME: DataFunctionTest
          AZURE_FUNCTIONAPP_PACKAGE_PATH: .
        run: |
          pip install azure-functions
          az login --service-principal --username ${{ secrets.AZURE_SERVICE_PRINCIPAL_USERNAME }} --password ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }} --tenant ${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT }}
          az functionapp deployment source config-zip --src ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group <resource-group-name>
